### PR TITLE
abw5248

### PR DESCRIPTION
**Pull request by Bomani**
added $PuzzleB.yaml

### CODE REVIEW

**Comment by decause** [comment]
@Bomani the dollar sign in the example was just there as a wild-card, and is not necessary in the file name.

If you type 'git mv $PuzzleB.yaml PuzzleB.yaml' and then commit and push, it will update this pull request automagically.

**Comment by Bomani** [comment]
@decause I tried that in the shell and it just gave me a fatal error. Im confused on what im supposed to do at this point, because I thought you were just supposed to accept the pull request, and that was the final step, did I do one of the previous steps wrong?

**Comment by ralphbean** [comment]
I think it is interpreting `PuzzleS`  as a shell variable.

**Comment by ralphbean** [comment]
Try `git mv \$PuzzleB.yml PuzzleB.yml`

**Comment by ralphbean** [comment]
Nm.  Looks like you got it already.  Apologies.  The github Android interface sucks.

**Comment by Bomani** [comment]
@decause  Hey Remy. What do I need to do to finish this assignment?

**Comment by decause** [comment]
@Bomani 

looks good!

:telescope:

**Pull request merged**
