### PR TITLE
Added gunpowderballet to people

### PR DESCRIPTION
**Pull request by bcc3139**

### CODE REVIEW

**Comment by decause** [comment]
@bcc3139 The "flavor" text at the top of your .yaml file, though it may seem insignificant, can be important. It provides a sort of "first impression" that folks looking through the people directory get when they find you. You should probably change that flavor text to something else, anything else, beside the flavor text I chose for mine ;) Fix it, and I'll merge.

**Comment by decause** [comment]
@bcc3139 see my comments above.

**Comment by bcc3139** [comment]
Changed now :) sorry it took so long

**Comment by decause** [comment]
:+1:

**Pull request merged**
