### PR TITLE
Create Kyung.yaml

### PR DESCRIPTION
**Pull request by kyung01**
Hey Professor. I am requesting pull up here. Please confirm this. Test Test

### CODE REVIEW

**Comment by kyung01** [comment]
I don't have a blog yet. Let me find the best place to blog.

**Comment by decause** [comment]
@kyung01 are you in the production studio course? If you are trying to add yourself to HFOSS course, the repository is at http://github.com/decause/hflossk. Take your .yaml file (when it is done) and send a pull request there.

Drop by IRC if you need any help.

**Comment by decause** [comment]
@kyung01 if you are still having trouble with your .yaml file, please stop by the FOSSBox and we'll help you out.

**Comment by decause** [comment]
Once your feed url has a "prodstud" tag, I'll merge :)

Good work today!

**Pull request merged**
